version: "3"

services:
  db-postgres-wisewallet:
    image: postgres:alpine
    ports:
      - "5437:5432"
    container_name: "bd-postgres-wisewallet"
    restart: always
    volumes:
      - ./bd-postgres-wisewallet:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
volumes:
  db-postgres-wisewallet: